apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stockviz
resources:
- ../../../base/migrate
patches:
  - target:
      kind: Job
      name: stockviz-migrate
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
images:
  - name: stockviz-api
    newName: stockviz-api
    newTag: dev
