apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- scheduler-deployment.yaml
- outbox-publisher-deployment.yaml
- trade-activity-deployment.yaml
- market-ingest-deployment.yaml
- market-analytics-deployment.yaml
- news-ingest-deployment.yaml
- news-sentiment-deployment.yaml
- sentiment-aggregate-deployment.yaml
