"""add price_bar_quarantine

Revision ID: 2c1a9603e92b
Revises: f7b3d91a2c04
Create Date: 2026-08-30 09:11:17.669972

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = "2c1a9603e92b"
down_revision: str | None = "f7b3d91a2c04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_bar_quarantine",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("interval", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column(
            "adjustment_semantics", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column("session_scope", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("prev_close", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["symbols.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_bar_quarantine_ticker_ts", "price_bar_quarantine", ["ticker", "ts"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_bar_quarantine_ticker_ts", table_name="price_bar_quarantine")
    op.drop_table("price_bar_quarantine")
    # ### end Alembic commands ###
