apiVersion: v1
kind: ConfigMap
metadata:
  name: stockviz-config
  namespace: stockviz
  labels:
    app.kubernetes.io/name: stockviz
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: stockviz
    app.kubernetes.io/version: 2.0.0
data:
  ENVIRONMENT: development
  ENABLE_SCHEDULER: 'false'
  KAFKA_BOOTSTRAP_SERVERS: stockviz-kafka-bootstrap:9092
  CORS_ORIGINS: http://localhost:3000
  API_URL: http://stockviz-api:8000
  NEXT_PUBLIC_API_URL: http://localhost:8000
  AUTH_TRUST_HOST: 'true'
  AUTH_URL: http://localhost:3000
  SENTIMENT_PROVIDER: none
